DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS genres;

CREATE TABLE authors
(
    id BIGSERIAL NOT NULL,
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    birthday VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE genres
(
    id BIGSERIAL NOT NULL,
    codegenre VARCHAR(2) NOT NULL,
    genre VARCHAR(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE books
(
    id BIGSERIAL NOT NULL,
    genre_id BIGINT REFERENCES genres(id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES authors(id) ON DELETE CASCADE,
    bookname VARCHAR(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id BIGSERIAL NOT NULL,
    message VARCHAR(255) NOT NULL,
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
    PRIMARY KEY (id)
)