spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/your_db_name

  shell:
    interactive:
      enabled: true

logging:
  level:
    ROOT: INFO

mongock:
  runner-type: initializingBean
  change-logs-scan-package: ru.otus.changelogs