spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/library?authSource=admin

  shell:
    interactive:
      enabled: true

logging:
  level:
    ROOT: INFO

mongock:
  runner-type: initializingBean
  change-logs-scan-package: ru.otus.changelogs