version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - ${PWD}/postgresql:/var/lib/postgresql

volumes:
  db-data:
    driver: local

# docker-compose down
# docker-compose up -d
# docker ps
# docker-compose down